# Generated by Django 4.0.4 on 2022-05-17 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='describetion',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='register',
        ),
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snack',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snack',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
